### ISSUE TITLE
本地实际测试Crawlergo爬不到项目主这么多页面

### ISSUE THREAD

**Issue by SummerSec** [ox01024/Xray_and_crwlergo_in_server#1]
本地实际测试Crawlergo爬不到项目主这么多页面？

**Comment by ox01024** [comment]
你的问题像极了机翻，请描述清晰你要反馈的内容

**Comment by SummerSec** [comment]
![sd](https://img-blog.csdnimg.cn/20200604152025256.png)

![在这里插入图片描述](https://img-blog.csdnimg.cn/20200604152108210.png)

对比一下我和你的爬到页面数量差距很大。

**Comment by ox01024** [comment]
请检测爬行任务是否完成，本项目并未提供crawlergo文件 有关于crawlergo的问题请查看 https://github.com/0Kee-Team/crawlergo

**Comment by SummerSec** [comment]
好的，我知道问题所在了，项目里的crawler_result.txt文件有很多是重复的。

**Comment by ox01024** [comment]
抱歉 可能是我测试了多次 但并未清理缓存
